version: "3"
 
services:
 
  nginx:
    image: nginx
    volumes:
      - ./docker/nginx/:/etc/nginx/conf.d/
    networks:
      - front
      - backend
    ports:
      - "80:80"
 
  apache:
    build: ./docker/apache
    volumes:
      - ./:/var/www/
      - ./docker/apache/php.ini:/usr/local/etc/php/php.ini
      - ./docker/apache/xdebug.so:/usr/local/lib/php/extensions/no-debug-non-zts-20131226/xdebug.so
      - ./docker/apache/docker-php-ext-mongo.ini:/usr/local/etc/php/conf.d/docker-php-ext-mongo.ini
    networks:
      - backend
      - clusternetwork
 
  db:
    image: "mysql:5.7"
    volumes:
      - ./docker/db:/var/lib/mysql
    environment:
         MYSQL_ROOT_PASSWORD: root
         MYSQL_DATABASE: local
         MYSQL_USER: local
         MYSQL_PASSWORD: local
    networks:
      - backend

  mongo:
    image: mongo
    #volumes:
    #  - ./docker/db:/var/lib/mysql
    #environment:
    #      MYSQL_ROOT_PASSWORD: root
    #      MYSQL_DATABASE: local
    #      MYSQL_USER: local
    #      MYSQL_PASSWORD: local
    networks:
      clusternetwork:
        ipv4_address: 172.16.0.14
    ports:
      - "27017:27017"
 
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      - PMA_HOST=db
      - PMA_USER=local
      - PMA_PASSWORD=local
    volumes:
      - /sessions
    networks:
      - backend
 
networks:
  front:
    external:
      name: front
  clusternetwork:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.0.0/24
  backend:
